
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Space Apps Challenge Kushimoto
subtitle: "NASA 主催の世界同時ハッカソン"
url: "http://ndrewtl.github.io" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: スタッフブログ
    desc: "Space Apps Challenge Kushimoto の実行委員によるスタッフブログです。"

  - cat: お知らせ
    desc: "Space Apps Challenge Kushimoto の実行委員からのお知らせ"
